SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE Resultado;
TRUNCATE TABLE Aplicacao;
TRUNCATE TABLE Avaliacao_Questao;
TRUNCATE TABLE Alternativa;
TRUNCATE TABLE QuestaoDiscursiva;
TRUNCATE TABLE QuestaoObjetiva;
TRUNCATE TABLE Questao;
TRUNCATE TABLE Avaliacao;

TRUNCATE TABLE Discente_Turma;
TRUNCATE TABLE Turma;
TRUNCATE TABLE Discente;
TRUNCATE TABLE Docente;
TRUNCATE TABLE Contrato;
TRUNCATE TABLE Usuario;

TRUNCATE TABLE Curso_Disciplina;
TRUNCATE TABLE Disciplina;
TRUNCATE TABLE Curso;

TRUNCATE TABLE Telefone;
TRUNCATE TABLE Campus;
TRUNCATE TABLE Instituicao;
TRUNCATE TABLE Bairro;
TRUNCATE TABLE Cidade;
TRUNCATE TABLE Estado;

TRUNCATE TABLE Auditoria;
TRUNCATE TABLE Resposta_Aluno;

SET FOREIGN_KEY_CHECKS = 1;